name: flutter_firebase_crud
version: 1.0.0+1
publish_to: none
description: Flutter Firebase CRUD App.
environment: 
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2

  #State Management and utils
  get: 4.6.1

  #FireBase
  firebase_core: 1.12.0
  cloud_firestore: 3.1.7

  #Network
  connectivity_plus: ^2.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

